<template>
  <img
    :src="iconPath"
    class="op-icon"
    :class="props.class"
    :alt="`${name} icon`"
  />
</template>

<script setup lang="ts">
// Naming things is hard! OPIcon - OpenPropertyIcon

interface Props {
  name: string
  class?: string
}
const defaultClasses = 'w-5 h-5'
const props = withDefaults(defineProps<Props>(), {
  class: defaultClasses,
})

const iconMap: Record<string, string> = {
  logo: '/op-icons/logo.svg',
  'user-code': '/op-icons/User-Code.svg',
  check: '/op-icons/Check.svg',
  'home-search': '/op-icons/Home-Search.svg',
  'building-community': '/op-icons/Building-Community.svg',
  apple: '/op-icons/Apple.svg',
  google: '/op-icons/Google.svg',
  facebook: '/op-icons/Facebook.svg',
  leftChevron: '/op-icons/backButtonIcon.svg',
  'create-account': '/images/createAccount.svg',
  userRegistration: '/op-icons/userRegistration.svg',
  house: '/op-icons/house.svg',
  apartment: '/op-icons/apartment.svg',
  land: '/op-icons/land.svg',
  commercial: '/op-icons/commercial.svg',
  semiDetached: '/op-icons/semiDetached.svg',
  terrace: '/op-icons/terrace.svg',
  singleFloorBungalow: '/op-icons/singleFloorBunglow.svg',
  garden: '/op-icons/garden.svg',
  publicTransport: '/op-icons/publicTransport.svg',
  driveway: '/op-icons/driveway.svg',
  mobileSignal: '/op-icons/mobileSignal.svg',
  goodEnergy: '/op-icons/goodEnergy.svg',
  closeToPublicPark: '/op-icons/closeToPublicPark.svg',
  closeToSchool: '/op-icons/closeToSchool.svg',
  homeOfficeSpace: '/op-icons/homeOfficeSpace.svg',
  radioUnchecked: '/op-icons/radioUnchecked.svg',
  radioChecked: '/op-icons/radioChecked.svg',
  addressSearch: '/images/addressSearch.png',
  search: '/op-icons/search.svg',
  passwordShow: '/op-icons/passwordShow.svg',
  passwordHide: '/op-icons/passwordHide.svg',
  checkboxUnchecked: '/op-icons/checkboxUnchecked.svg',
  checkboxChecked: '/op-icons/checkboxChecked.svg',
  explore: '/op-icons/bottom-nav/explore.svg',
  passport: '/op-icons/bottom-nav/passport.svg',
  marketplace: '/op-icons/bottom-nav/marketplace.svg',
  rewards: '/op-icons/bottom-nav/rewards.svg',
  learn: '/op-icons/bottom-nav/learn.svg',
  propertySearch: '/op-icons/explore/propertySearch.png',
  accessPassport: '/op-icons/property-nav/accessPassport.svg',
  registerInterest: '/op-icons/property-nav/registerInterest.svg',
  saveProperty: '/op-icons/property-nav/saveProperty.svg',
  tapOwner: '/op-icons/property-nav/tapOwner.svg',
  buyer: '/op-icons/passportview/buyer.svg',
  seller: '/op-icons/passportview/seller.svg',
  pin: '/op-icons/passportview/pin.svg',
  caretDown: '/op-icons/passportview/caretDown.svg',
  addCollaborator: '/op-icons/passportview/addCollaborator.svg',
  list: '/op-icons/passportview/list.svg',
  map: '/op-icons/passportview/map.svg',
  caretRight: '/op-icons/passportview/caretRight.svg',
  instructions: '/op-icons/passportview/instructions.svg',
  ownershipProfile: '/op-icons/passportview/instructions.svg',
  boundaries: '/op-icons/passportview/boundaries.svg',
  disputesAndComplaints: '/op-icons/passportview/disputes-and-complaints.svg',
  noticesAndProposals: '/op-icons/passportview/notices-and-proposals.svg',
  alterationsAndPlanning: '/op-icons/passportview/alterations-and-planning.svg',
  guaranteesAndWarranties:
    '/op-icons/passportview/guarantees-and-warranties.svg',
  insurance: '/op-icons/passportview/insurance.svg',
  environmental: '/op-icons/passportview/environmental.svg',
  rightsAndInformalArrangements:
    '/op-icons/passportview/rights-and-informal-arrangements.svg',
  parking: '/op-icons/passportview/parking.svg',
  otherCharges: '/op-icons/passportview/other-charges.svg',
  occupiers: '/op-icons/passportview/occupiers.svg',
  services: '/op-icons/passportview/services.svg',
  transactionInformation: '/op-icons/passportview/transaction-information.svg',
  fixturesAndFittings: '/op-icons/passportview/fixture-and-fittings.svg',
  leasehold: '/op-icons/passportview/leasehold.svg',
  titleDeedsAndPlan: '/op-icons/passportview/title-deeds-and-plan.svg',
  searches: '/op-icons/passportview/searches.svg',
  info: '/op-icons/passportview/steps/info.svg',
  playIcon: '/op-icons/passportview/steps/play-icon.svg',
  rewardBox: '/op-icons/passportview/steps/rewardBox.svg',
  appleNew: '/icons/AppleNewIcon.svg',
  googleNew: '/icons/GoogleNewIcon.svg',
  facebookNew: '/icons/FacebookNewIcon.svg',
  leftChevronWhite: '/icons/leftChevronWhite.svg',
  wishlist: '/icons/wishlist.svg',
  share: '/icons/share.svg',
  messages: '/op-icons/property/messages.svg',
  airdrop: '/op-icons/property/airdrop.svg',
  instagram: '/op-icons/property/instagram.svg',
  messagesLight: '/op-icons/property/messagesLight.svg',
  whatsapp: '/op-icons/property/whatsapp.svg',
  matchToBuyers: '/op-icons/passportview/matchToBuyers.svg',
  pending: '/op-icons/passportview/pending.svg',
  upload: '/op-icons/passportview/upload.svg',
  scan: '/op-icons/passportview/scan.svg',
  underReview: '/op-icons/passportview/steps/underReview.svg',
  infoCircle: '/op-icons/passportview/steps/infoCircle.svg',
  expertIcon: '/op-icons/passportview/steps/expertIcon.svg',
  progressMan: '/op-icons/passportview/progressMan.svg',
  roadLeftToRight: '/op-icons/passportview/roadLeftToRight.svg',
  roadRightToLeft: '/op-icons/passportview/roadRightToLeft.svg',
  giftIcon: '/op-icons/passportview/giftIcon.svg',
  mapBackgroundTile: '/op-icons/passportview/mapBackgroundTile.svg',
  pointsLock: '/op-icons/passportview/pointsLock.svg',
  lightBulb: '/op-icons/passportview/lightBulb.svg',
  addMoreButton: '/op-icons/passportview/addMoreButton.svg',
  backgroundImage: '/op-icons/backgroundImage.jpeg',
  pendingCircle: '/op-icons/passportview/pendingCircle.svg',
  boundariesMap: '/op-icons/passportview/boundariesMap.svg',
  ownershipProfileNotes: '/op-icons/passportview/ownershipProfileNotes.svg',
  visitLink: '/op-icons/passportview/visitLink.svg',
  helpIcon: '/op-icons/passportview/steps/helpIcon.svg',
  environmentalNotes: '/op-icons/passportview/steps/environmentalNotes.svg',
  dog: '/op-icons/passportview/map/dog.svg',
  lampPost: '/op-icons/passportview/map/lampPost.svg',
  orangeDog: '/op-icons/passportview/map/orangeDog.svg',
  post: '/op-icons/passportview/map/post.svg',
  postInverted: '/op-icons/passportview/map/postInverted.svg',
  tree: '/op-icons/passportview/map/tree.svg',
  walkingLady: '/op-icons/passportview/map/walkingLady.svg',
  sellersHub: '/op-icons/explore/sellersHub.svg',
  buyersHub: '/op-icons/explore/buyersHub.svg',
  findTrustedUsers: '/op-icons/explore/findTrustedUsers.svg',
  like: '/op-icons/explore/like.svg',
  dislike: '/op-icons/explore/dislike.svg',
  passportPercentage: '/op-icons/explore/passportPercentage.svg',
  sqft: '/op-icons/explore/sqft.svg',
  verified: '/op-icons/explore/verified.svg',
  bedroom: '/op-icons/explore/bedroom.svg',
  bathroom: '/op-icons/explore/bathroom.svg',
  matchPercentage: '/op-icons/explore/matchPercentage.svg',
  searchSuggestions: '/op-icons/explore/searchSuggestions.svg',
  currentLocation: '/op-icons/explore/currentLocation.svg',
  drawOnMaps: '/op-icons/explore/drawOnMap.svg',
  passportAvailable: '/op-icons/explore/passportAvailable.svg',
  chevronRight: '/op-icons/explore/chevronRight.svg',
  searchResults: '/op-icons/explore/searchResults.svg',
  bedroomWhite: '/op-icons/property/bedroomWhite.svg',
  bathroomWhite: '/op-icons/property/bathroomWhite.svg',
  sqftWhite: '/op-icons/property/sqftWhite.svg',
  floorPlan: '/op-icons/property/floorPlan.png',
  titleNumber: '/op-icons/property/titleNumber.svg',
  epcRating: '/op-icons/property/epcRating.svg',
  tenure: '/op-icons/property/tenure.svg',
  yearBuilt: '/op-icons/property/yearBuilt.svg',
  externalLink: '/op-icons/property/externalLink.svg',
  locationFilled: '/op-icons/property/locationFilled.svg',
  train: '/op-icons/property/train.svg',
  filterExplore: '/op-icons/filter/explore.svg',
  filterPriceRange: '/op-icons/filter/priceRange.svg',
  filterPropertyType: '/op-icons/filter/propertyType.svg',
  exploreExternalLink: '/op-icons/explore/externalLink.svg',
  nationalRailLogo: '/op-icons/explore/nationalRailLogo.svg',
  mrtLogo: '/op-icons/explore/mrt.svg',
  trainWhite: '/op-icons/explore/trainWhite.svg',
  verifyOwnership: '/op-icons/verifyOwnership/verifyOwnership.svg',
  ownershipVerified: '/op-icons/verifyOwnership/ownershipVerified.svg',
  governmentLogo: '/op-icons/verifyOwnership/governmentLogo.svg',
  startVerification: '/op-icons/verifyOwnership/startVerification.svg',
  nothingSaved: '/op-icons/verifyOwnership/nothingSaved.svg',
  verifiedFilled: '/op-icons/verifyOwnership/verifiedFilled.svg',
  successfulProcess: '/op-icons/verifyOwnership/successfulProcess.svg',
  verifiedDocument: '/op-icons/verifyOwnership/verifiedDocument.svg',
  propertyImage: '/op-icons/temp/property.svg',
  file: '/op-icons/temp/file.svg',
}

const iconPath = computed(() => {
  return iconMap[props.name] || '/op-icons/default.svg'
})
</script>
